# Generated by Django 3.0.4 on 2020-04-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmanager', '0003_auto_20200406_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmanager',
            name='description',
            field=models.CharField(max_length=1500),
        ),
    ]
