# Generated by Django 3.0.4 on 2020-05-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmanager', '0004_auto_20200409_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmanager',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
