# Generated by Django 3.0.4 on 2020-05-02 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('is_published', models.BooleanField(default=True)),
                ('article', models.CharField(max_length=1500)),
                ('publish_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
