# Generated by Django 3.0.4 on 2020-05-10 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_remove_contacts_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='surname',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
