# Generated by Django 3.0.4 on 2020-05-10 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_contacts_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='surname',
        ),
    ]
